version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
